### ISSUE TITLE
how to open GUI

### ISSUE THREAD

**Issue by liyang53719** [microdynamics-cpu/tree-core-ide#1]
I listened to your speech in Shanghai last week. I am very interested in this tool.
But is there any documentation on how to use this tool?

thank you

**Comment by maksyuki** [comment]
Thank for your attention :smile: . Now, because this IDE is still **under development**, there's not an official documentation yet. In our development plan, the init public vision will be released in September. Of course, if you have any question,  you can just open a new issue in this repo. We'll reply to you as soon as possible.

**Comment by liyang53719** [comment]
thank you for your reply.
I saw many GUI demonstrations in your speech.

So the first two questions:
How do I open this ide?
How can I read the v file to get the schematic?


Thank you

**Comment by maksyuki** [comment]
Because the code of the UI system is still under testing in our local repo, there's not in the remote repo. That means now you can not use these features. Read the v file will simple, like vivado or modelsim, you only need to do is pressing one button. But just like I said before, these features are still under development:sweat_smile: . For the next two months, we'll add some more surprising features, improve the UI system and fix some bugs. So maybe you need to wait some time :sweat_smile: .

**Comment by liyang53719** [comment]
thank you for your reply.
I will continue to pay attention.
Hope it will be done soon.
